<?php
/** @var $block Index */

use AlphaTeam\Report\Block\Adminhtml\CustomReport\Index;

$actionUrl = $block->getRunUrl();
$options = $block->getReportTypeOptions();

?>

<div class="alphateam-custom-reports-wrapper">
    <div class="alphateam-custom-reports">
        <form method="post" action="<?= $block->escapeUrl($actionUrl) ?>" class="alphateam-customreport-form"
              data-mage-init='{"AlphaTeam_Report/js/report": {}}'>
            <?= $block->getBlockHtml('formkey'); ?>

            <div class="admin__field alphateam-report-row">
                <label class="admin__field-label" for="report_type">
                    <span><?= $block->escapeHtml(__('Select report')) ?></span>
                </label>

                <div class="admin__field-control" style="margin-bottom:0;">
                    <select name="report_type" id="report_type" class="admin__control-select">
                        <?php foreach ($options as $option): ?>
                            <option value="<?= $block->escapeHtmlAttr($option['value']) ?>">
                                <?= $block->escapeHtml($option['label']) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <div class="admin__field-control mt-0">
                    <button type="submit" class="action-default scalable">
                        <span><?= $block->escapeHtml(__('Generate Report')) ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
